server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com  #euraka服务端的实例名字
  client:
    register-with-eureka: false
    fetch-registry: false
    #设置与euraka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka